# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0009_auto_20160401_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': ('is_publish', 'is_publish')},
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 12, 54, 1, 995023)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 12, 54, 1, 996118)),
        ),
    ]
