# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0010_auto_20160401_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': ('is_mark', 'is_mark')},
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 13, 34, 4, 637486)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 13, 34, 4, 638460)),
        ),
    ]
