# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0013_auto_20160401_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('is_mark', 'mark'),)},
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 14, 23, 22, 282081)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 14, 23, 22, 283081)),
        ),
    ]
