# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjangoApp', '0015_auto_20160401_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='like',
            old_name='comment_like_id',
            new_name='Comment_like_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_like_id',
            new_name='User_like_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 15, 7, 45, 40917)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 15, 7, 45, 41898)),
        ),
        migrations.AddField(
            model_name='mark',
            name='Article_mark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.Comment'),
        ),
        migrations.AddField(
            model_name='mark',
            name='User_mark_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
